### PR TITLE
Corsica scenery

### PR DESCRIPTION
**Pull request by hsanjuan**
@jmbau is this good to go?

### CODE REVIEW

**Comment by jmbau** [comment]
For now, transparent color of altitude lakes surface has been replaced by some blue one. No "splash", but a better look...
Ready to go.

**Comment by jmbau** [comment]
I don't now if my today commits are included in this PR or not...

**Comment by hsanjuan** [comment]
> I don't now if my today commits are included in this PR or not...

They are!

Once I merge, if you want to add more things, branch off from master into a new branch and make a new PR.

**Review by hsanjuan — COMMENTED** [review]
I'm very much looking forward to playing these missions!

**Pull request merged**
